tabulados:
  - name: Perfil seleccionado
    tables:
      - freq: "SECTOR"
      - freq: "vivienda"
      - freq: "hgr_n"
      - freq: "nvivienda__0"
      - freq: "nvivienda__0c"
      - freq: "nvivienda__1"
      - freq: "nvivienda__1c"
      - freq: "nvivienda__2"
      - crosstab:
          row: "SECTOR"
          col: "vivienda"
