tabulados:
  - name: Perfil seleccionado
    tables:
      - freq: "SECTOR"
      - freq: "id_h"
      - freq: "id_v"
      - freq: "sexom"
      - freq: "sexoh"
      - freq: "sexonh"
      - freq: "sexonm"
      - freq: "sexo"
      - crosstab:
          row: "SECTOR"
          col: "id_h"
