tabulados:
  - name: Perfil automático
    tables:
      - freq: "nvivienda__1"
      - freq: "enc"
      - freq: "sexo_jefe_estr_hg1"
      - freq: "p004"
      - freq: "p004nm"
      - freq: "p006"
      - crosstab:
          row: "nvivienda__1"
          col: "enc"
